# Generated by Django 5.2.3 on 2025-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'verbose_name': 'Nota Sisu', 'verbose_name_plural': 'Notas Sisu'},
        ),
        migrations.AddField(
            model_name='nota',
            name='CO_CAMPUS',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cód. Campus'),
        ),
        migrations.AddField(
            model_name='nota',
            name='CO_IES',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cód. IES'),
        ),
        migrations.AddField(
            model_name='nota',
            name='CO_IES_CURSO',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cód. IES Curso'),
        ),
        migrations.AddField(
            model_name='nota',
            name='DS_GRAU',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Grau'),
        ),
        migrations.AddField(
            model_name='nota',
            name='DS_MOD_CONCORRENCIA',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modalidade Concorrência'),
        ),
        migrations.AddField(
            model_name='nota',
            name='DS_TURNO',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='nota',
            name='SG_UF_CAMPUS',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF Campus'),
        ),
    ]
