# Generated by Django 5.2.3 on 2025-06-18 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0002_alter_nota_options_nota_co_campus_nota_co_ies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='conteudo',
        ),
    ]
