# Generated by Django 5.2.3 on 2025-06-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0003_remove_nota_conteudo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_humanas',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Nota Ciências Humanas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_linguagens',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Nota Linguagens'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_matematica',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Nota Matemática'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_natureza',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Nota Ciências da Natureza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nota',
            name='nota_redacao',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Nota Redação'),
            preserve_default=False,
        ),
    ]
