# Generated by Django 5.2.3 on 2025-06-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisu', '0004_nota_conteudo_nota_nota_humanas_nota_nota_linguagens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='conteudo',
        ),
    ]
